name: Bounty
api: 3.0.0
main: Infernus101\Main
version: 2.0.1-PMnS
author: VMPE Development Team, princepines
description: Bounty plugin for Faction servers.
commands:
  bounty:
    description: "Bounty help"
